# Generated by Django 3.2 on 2021-04-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('1', 'Action'), ('2', 'Drama'), ('4', 'Something_new'), ('3', 'Melodrama')], max_length=40)),
            ],
        ),
    ]
